---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
# Spillover: Spatial Change Point Estimation Due to Spillover from a Point Source

## Statistical Model
$$Y_i\left(\textbf{s}_i\right)|p_i\left(\textbf{s}_i\right) \stackrel{\text{ind}}{\sim} \text{Binomial}\left(c_i, p_i\left(\textbf{s}_i\right)\right),\ i=1,...,n;$$

$$\log\left(\frac{p_i\left(\textbf{s}_i\right)}{1 - p_i\left(\textbf{s}_i\right)}\right) = \textbf{x}_i^{\text{T}} \boldsymbol{\beta} + \lambda g\left(||\textbf{s}_i - \textbf{s}_p||; \theta\right) + w\left(\textbf{s}_i\right);$$

$$\boldsymbol{w}=\left(w\left(\textbf{s}^*_1\right), ..., w\left(\textbf{s}^*_m\right)\right)^{\text{T}}| \sigma^2_w, \phi \sim \text{MVN}\left(\boldsymbol{0}_m, \sigma^2_w\Sigma\left(\phi\right)\right);$$

$$\Sigma\left(\phi\right)_{ij} = \left\{ \begin{array}{ll}
                                          1-1.5\phi ||\textbf{s}^*_i - \textbf{s}^*_j|| + 0.5\left(\phi ||\textbf{s}^*_i - \textbf{s}^*_j||\right)^3, & \mbox{if $0 \leq ||\textbf{s}^*_i - \textbf{s}^*_j|| \leq 1/\phi$};\\
                                         0, & \mbox{if $||\textbf{s}^*_i - \textbf{s}^*_j|| \geq 1/\phi$}.\end{array} \right.$$
                                        

* $\textbf{s}_p$: Location of the point source;

* $\textbf{s}_i \in \left\{\textbf{s}^*_1, ..., \textbf{s}^*_m\right\}$ for all $i$, where $m < n$ is the number of unique spatial locations;

* $\boldsymbol{0}_m$: Length $m$ vector with each entry equal to zero.

## $g\left(||\textbf{s}_i - \textbf{s}_p||; \theta\right)$ Options
  
* Change Point:  $I\left(||\textbf{s}_i - \textbf{s}_p|| \leq \theta\right)$;
  
* Exponential:  $I\left(||\textbf{s}_i - \textbf{s}_p|| \leq \theta\right) \exp\left\{-||\textbf{s}_i - \textbf{s}_p||\right\}$;
  
* Gaussian:  $I\left(||\textbf{s}_i - \textbf{s}_p|| \leq \theta\right) \exp\left\{-\left(||\textbf{s}_i - \textbf{s}_p||\right)^2\right\}$.


## Prior Information
$\beta_j, \lambda \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\delta}\right),\ j=1,...,p;$

* $p$: Length of $\textbf{x}_i$ vector (same for all $i$);

* Default setting: $\sigma^2_{\delta} = 10,000.$

$\theta \sim \text{Uniform}\left(a_{\theta}, b_{\theta}\right)$;

* Default settings: $a_{\theta}= \min\left\{||\textbf{s}_i - \textbf{s}_p||: i=1,...,n\right\}$, $b_{\theta}=\max\left\{||\textbf{s}_i - \textbf{s}_p||: i=1,...,n\right\}$. 

$\sigma^2_{w} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{w}}, b_{\sigma^2_{w}}\right);$

* Default setting: $a_{\sigma^2_{w}} = 3$, $b_{\sigma^2_{w}} = 2.$

$\phi \sim \text{Gamma}\left(\alpha_{\phi}, \beta_{\phi}\right);$

* Default setting: $\alpha_{\phi} = 1$, $\beta_{\phi} = 1.$

## Default Initial Values
* $\beta_j = \lambda = 0$ for all $j$;

* $\theta = \left(b_{\theta} - a_{\theta}\right)/2$;

* $w\left(\textbf{s}_i\right) = 0$ for all $i$;

* $\sigma^2_w = 1$;

* $\phi = 0.01\max\left\{||\textbf{s}_i - \textbf{s}_p||: i=1,...,n\right\}$.

