# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Spillover <- function(mcmc_samples, spillover_covar_def, y, x, distance_to_ps, z, spatial_dists, metrop_var_phi_trans, metrop_var_theta_trans, sigma2_regress_prior = NULL, a_theta_prior = NULL, b_theta_prior = NULL, alpha_phi_prior = NULL, beta_phi_prior = NULL, alpha_sigma2_w_prior = NULL, beta_sigma2_w_prior = NULL, beta_init = NULL, lambda_init = NULL, w_init = NULL, phi_init = NULL, theta_init = NULL, sigma2_w_init = NULL) {
    .Call(`_Spillover_Spillover`, mcmc_samples, spillover_covar_def, y, x, distance_to_ps, z, spatial_dists, metrop_var_phi_trans, metrop_var_theta_trans, sigma2_regress_prior, a_theta_prior, b_theta_prior, alpha_phi_prior, beta_phi_prior, alpha_sigma2_w_prior, beta_sigma2_w_prior, beta_init, lambda_init, w_init, phi_init, theta_init, sigma2_w_init)
}

beta_lambda_update <- function(x, spillover_covar, z, w_aux, gamma, w_old, sigma2_regress) {
    .Call(`_Spillover_beta_lambda_update`, x, spillover_covar, z, w_aux, gamma, w_old, sigma2_regress)
}

neg_two_loglike_update <- function(y, x, spillover_covar, z, beta, lambda, w) {
    .Call(`_Spillover_neg_two_loglike_update`, y, x, spillover_covar, z, beta, lambda, w)
}

phi_update <- function(spatial_dists, phi_old, w, sigma2_w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_Spillover_phi_update`, spatial_dists, phi_old, w, sigma2_w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_Spillover_rcpp_pgdraw`, b, c)
}

sigma2_w_update <- function(w, corr_inv, alpha_sigma2_w, beta_sigma2_w) {
    .Call(`_Spillover_sigma2_w_update`, w, corr_inv, alpha_sigma2_w, beta_sigma2_w)
}

spatial_corr_fun <- function(phi, spatial_dists) {
    .Call(`_Spillover_spatial_corr_fun`, phi, spatial_dists)
}

theta_update <- function(x, z, distance_to_ps, theta_old, w_aux, gamma, beta, lambda, w, spillover_covar_temp, spillover_covar_def, a_theta, b_theta, metrop_var_theta_trans, acctot_theta_trans) {
    .Call(`_Spillover_theta_update`, x, z, distance_to_ps, theta_old, w_aux, gamma, beta, lambda, w, spillover_covar_temp, spillover_covar_def, a_theta, b_theta, metrop_var_theta_trans, acctot_theta_trans)
}

w_aux_update <- function(y, x, spillover_covar, z, beta_old, lambda_old, w_old) {
    .Call(`_Spillover_w_aux_update`, y, x, spillover_covar, z, beta_old, lambda_old, w_old)
}

w_update <- function(x, spillover_covar, z, w_aux, gamma, beta, lambda, sigma2_w_old, corr_inv) {
    .Call(`_Spillover_w_update`, x, spillover_covar, z, w_aux, gamma, beta, lambda, sigma2_w_old, corr_inv)
}

